version: '2.1'
orbs:
  orb-tools: circleci/orb-tools@10
  deepsource: deepsource/test-coverage@dev:alpha
  python: circleci/python@0.2.1
jobs:
  integration-test-for-test-coverage:
    executor: python/default
    steps:
      - checkout
      - run: pip install pytest-cov
      - run: pytest --cov=./ --cov-report=xml
      - deepsource/report:
          key: python
          coverage-file: ./coverage.xml

workflows:
  lint-validate-test-publish:
    jobs:
      - orb-tools/lint
      - orb-tools/pack:
          requires: [orb-tools/lint]
      - orb-tools/publish-dev:
          orb-name: deepsource/test-coverage
          validate: true
          requires: [orb-tools/pack]
      - integration-test-for-test-coverage:
          requires: [orb-tools/publish-dev]
      - orb-tools/dev-promote-prod-from-commit-subject:
          orb-name: deepsource/test-coverage
          fail-if-semver-not-indicated: true
          publish-version-tag: false
          add-pr-comment: false
          requires: [integration-test-for-test-coverage]
          filters:
            branches:
              only: master
