version: 2.1
description:

commands:
  hello:
    description: Greet the user politely
    parameters:
      username:
        type: string
        description: A name of the user to greet
    steps:
      - run: curl https://deepsource.io/cli | sh
